# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\enhance_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Enhance_Dialog(object):
    def setupUi(self, Enhance_Dialog):
        Enhance_Dialog.setObjectName("Enhance_Dialog")
        Enhance_Dialog.resize(645, 436)
        Enhance_Dialog.setMinimumSize(QtCore.QSize(645, 436))
        Enhance_Dialog.setMaximumSize(QtCore.QSize(645, 436))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        Enhance_Dialog.setFont(font)
        self.lineEdit_w2_openPDF = QtWidgets.QLineEdit(Enhance_Dialog)
        self.lineEdit_w2_openPDF.setGeometry(QtCore.QRect(17, 20, 500, 40))
        self.lineEdit_w2_openPDF.setObjectName("lineEdit_w2_openPDF")
        self.pushButton_w2_start = QtWidgets.QPushButton(Enhance_Dialog)
        self.pushButton_w2_start.setGeometry(QtCore.QRect(527, 268, 100, 40))
        self.pushButton_w2_start.setObjectName("pushButton_w2_start")
        self.label_w2_tips = QtWidgets.QLabel(Enhance_Dialog)
        self.label_w2_tips.setGeometry(QtCore.QRect(16, 326, 609, 55))
        self.label_w2_tips.setObjectName("label_w2_tips")
        self.pushButton_w2_openPDF = QtWidgets.QPushButton(Enhance_Dialog)
        self.pushButton_w2_openPDF.setGeometry(QtCore.QRect(527, 20, 100, 40))
        self.pushButton_w2_openPDF.setObjectName("pushButton_w2_openPDF")
        self.progressBar_w2 = QtWidgets.QProgressBar(Enhance_Dialog)
        self.progressBar_w2.setGeometry(QtCore.QRect(17, 268, 495, 40))
        self.progressBar_w2.setProperty("value", 0)
        self.progressBar_w2.setObjectName("progressBar_w2")
        self.Slider_w2_colorSet = QtWidgets.QSlider(Enhance_Dialog)
        self.Slider_w2_colorSet.setGeometry(QtCore.QRect(150, 88, 350, 30))
        self.Slider_w2_colorSet.setMaximum(50)
        self.Slider_w2_colorSet.setSingleStep(1)
        self.Slider_w2_colorSet.setProperty("value", 10)
        self.Slider_w2_colorSet.setTracking(False)
        self.Slider_w2_colorSet.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_w2_colorSet.setObjectName("Slider_w2_colorSet")
        self.Slider_w2_contrastSet = QtWidgets.QSlider(Enhance_Dialog)
        self.Slider_w2_contrastSet.setGeometry(QtCore.QRect(150, 128, 350, 30))
        self.Slider_w2_contrastSet.setMaximum(50)
        self.Slider_w2_contrastSet.setProperty("value", 10)
        self.Slider_w2_contrastSet.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_w2_contrastSet.setObjectName("Slider_w2_contrastSet")
        self.Slider_w2_brightnessSet = QtWidgets.QSlider(Enhance_Dialog)
        self.Slider_w2_brightnessSet.setGeometry(QtCore.QRect(150, 208, 350, 30))
        self.Slider_w2_brightnessSet.setMaximum(50)
        self.Slider_w2_brightnessSet.setProperty("value", 10)
        self.Slider_w2_brightnessSet.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_w2_brightnessSet.setObjectName("Slider_w2_brightnessSet")
        self.Slider_w2_sharpnessSet = QtWidgets.QSlider(Enhance_Dialog)
        self.Slider_w2_sharpnessSet.setGeometry(QtCore.QRect(150, 168, 350, 30))
        self.Slider_w2_sharpnessSet.setMaximum(50)
        self.Slider_w2_sharpnessSet.setProperty("value", 10)
        self.Slider_w2_sharpnessSet.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_w2_sharpnessSet.setObjectName("Slider_w2_sharpnessSet")
        self.label_w2_sharpnessValue = QtWidgets.QLabel(Enhance_Dialog)
        self.label_w2_sharpnessValue.setGeometry(QtCore.QRect(512, 168, 40, 30))
        self.label_w2_sharpnessValue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_w2_sharpnessValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_w2_sharpnessValue.setObjectName("label_w2_sharpnessValue")
        self.label_w2_colorValue = QtWidgets.QLabel(Enhance_Dialog)
        self.label_w2_colorValue.setGeometry(QtCore.QRect(512, 88, 40, 30))
        self.label_w2_colorValue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_w2_colorValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_w2_colorValue.setObjectName("label_w2_colorValue")
        self.label_w2_contrastValue = QtWidgets.QLabel(Enhance_Dialog)
        self.label_w2_contrastValue.setGeometry(QtCore.QRect(512, 128, 40, 30))
        self.label_w2_contrastValue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_w2_contrastValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_w2_contrastValue.setObjectName("label_w2_contrastValue")
        self.label_w2_brightnessValue = QtWidgets.QLabel(Enhance_Dialog)
        self.label_w2_brightnessValue.setGeometry(QtCore.QRect(512, 208, 40, 30))
        self.label_w2_brightnessValue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_w2_brightnessValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_w2_brightnessValue.setObjectName("label_w2_brightnessValue")
        self.label = QtWidgets.QLabel(Enhance_Dialog)
        self.label.setGeometry(QtCore.QRect(38, 88, 90, 30))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Enhance_Dialog)
        self.label_2.setGeometry(QtCore.QRect(38, 128, 90, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Enhance_Dialog)
        self.label_3.setGeometry(QtCore.QRect(38, 208, 90, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Enhance_Dialog)
        self.label_4.setGeometry(QtCore.QRect(38, 168, 90, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.checkBox_w2_saveAllImage = QtWidgets.QCheckBox(Enhance_Dialog)
        self.checkBox_w2_saveAllImage.setGeometry(QtCore.QRect(336, 400, 289, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        self.checkBox_w2_saveAllImage.setFont(font)
        self.checkBox_w2_saveAllImage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_w2_saveAllImage.setObjectName("checkBox_w2_saveAllImage")
        self.line_3 = QtWidgets.QFrame(Enhance_Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 388, 625, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Enhance_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Enhance_Dialog)

    def retranslateUi(self, Enhance_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Enhance_Dialog.setWindowTitle(_translate("Enhance_Dialog", "文本增强"))
        self.pushButton_w2_start.setText(_translate("Enhance_Dialog", "开始处理"))
        self.label_w2_tips.setText(_translate("Enhance_Dialog", "未打开文件"))
        self.pushButton_w2_openPDF.setText(_translate("Enhance_Dialog", "打开PDF"))
        self.label_w2_sharpnessValue.setText(_translate("Enhance_Dialog", "1.0"))
        self.label_w2_colorValue.setText(_translate("Enhance_Dialog", "1.0"))
        self.label_w2_contrastValue.setText(_translate("Enhance_Dialog", "1.0"))
        self.label_w2_brightnessValue.setText(_translate("Enhance_Dialog", "1.0"))
        self.label.setText(_translate("Enhance_Dialog", "色彩平衡"))
        self.label_2.setText(_translate("Enhance_Dialog", "对比度"))
        self.label_3.setText(_translate("Enhance_Dialog", "亮度"))
        self.label_4.setText(_translate("Enhance_Dialog", "锐度"))
        self.checkBox_w2_saveAllImage.setText(_translate("Enhance_Dialog", "保存所有拆分增强后的图片"))

